#!/bin/sh
# Uninstall all non-whitelisted Homebrew formulae

# Exit on any command failures
set -e

BREW_CLEAN_WHITELIST=~/.brew-cleanup-installed
[ -s $BREW_CLEAN_WHITELIST ]
BREW_LIST=$TMPDIR/brew-list

# comm needs both lists to be sorted so ensure the dotfile is sorted first.
sort --unique ~/.brew-cleanup-installed --output ~/.brew-cleanup-installed
brew list > $BREW_LIST
comm -13 $BREW_CLEAN_WHITELIST $BREW_LIST | xargs brew uninstall
rm $BREW_LIST
