#!/bin/sh
if [ -z "$*" ]
then
  echo "Error: git command needed!" >&2
  exit 1
fi

/usr/bin/git --version
/usr/bin/git "$@"
echo

git --version
git "$@"
echo

brew info libgit2 --json=v1 | jq -r '.[0].name + " " + .[0].installed[0].version'

# shellcheck disable=SC2145
"$(brew --prefix libgit2)"/share/libgit2/examples/"$@"
